import random


def get_progress_bar(progress, total):
    filled = int(10 * progress / total)
    return '▓' * filled + '░' * (10 - filled)

def get_rank_emoji(rank, total):
    if rank == 1:
        return "👑"
    elif rank == 2:
        return "🥈"
    elif rank == 3:
        return "🥉"
    elif rank >= total - 2:
        return "💩"
    else:
        return "🧙"  # Default emoji for other ranks


def get_insult():
    insults = [
    # Bankers
    "Too busy counting other people's money to raid?",
    "Afraid raiding might cut into your 'denying loans' time?",
    "Still trying to figure out how to charge a fee for joining the raid?",
    "Busy practicing your 'I'm sorry, but your credit score is too low' speech?",
    "Worried raiding might interfere with your yacht shopping?",
    "Too occupied calculating interest rates on your guild's repair bills?",
    "Afraid you might miss a chance to foreclose on someone's virtual house?",
    "Busy trying to convince the raid boss to open a high-interest savings account?",
    "Worried that raiding doesn't offer enough opportunities for hidden fees?",
    "Too occupied polishing your gold-plated calculator?",
    "Afraid you might have to interact with the 99% in the raid?",
    "Busy trying to figure out how to outsource your raiding responsibilities?",
    "Worried that your monocle might fall off during an intense boss fight?",
    "Too occupied adjusting the thermostat in your ivory tower?",
    "Afraid that raiding might cut into your 'swimming in coins' time?",
    "Busy trying to convince the guild to switch to a subscription-based model?",
    "Worried that your suit might get wrinkled during the raid?",
    "Too occupied planning your next bailout request?",
    "Afraid that raiding might expose you to the concept of 'fair play'?",
    "Busy trying to deposit your raid loot in an offshore account?",

    # Insurance Workers
    "Too busy denying claims to join the raid?",
    "Afraid the raid boss might not be covered under your policy?",
    "Still calculating the premiums for raid wipe insurance?",
    "Busy trying to find the 'Act of God' clause for dragon attacks?",
    "Worried that raiding might be considered a pre-existing condition?",
    "Too occupied writing up the fine print for the guild's insurance policy?",
    "Afraid you might have to pay out if the raid is actually successful?",
    "Busy trying to convince the healer to buy life insurance?",
    "Worried that raiding might be classified as 'high-risk behavior'?",
    "Too occupied adjusting rates based on the tank's survivability?",
    "Afraid that your actuarial tables don't account for respawns?",
    "Busy trying to sell volcano insurance in Molten Core?",
    "Worried that you can't weasel out of covering raid damage?",
    "Too occupied creating a 'raiding under the influence' policy?",
    "Afraid that your risk assessment skills might be challenged in the raid?",
    "Busy trying to explain why 'death by gnome' isn't covered?",
    "Worried that raiding might actually be fun and ruin your image?",
    "Too occupied calculating the statistical likelihood of loot drops?",
    "Afraid that your soul-sucking aura might actually help in the raid?",
    "Busy trying to find a loophole in the 'resurrection' clause?",

    # Software Developers
    "Too busy debugging your life to join the raid?",
    "Afraid that raiding might force you to interact with users?",
    "Still trying to compile your courage to join the group?",
    "Busy writing 'Hello World' in your 50th programming language?",
    "Worried that raiding doesn't allow for enough coffee breaks?",
    "Too occupied trying to center a div in your UI?",
    "Afraid that your raid rotation might not be optimized for O(1) time complexity?",
    "Busy trying to convince the raid leader to use Agile methodologies?",
    "Worried that you can't Google solutions during the boss fight?",
    "Too occupied refactoring your gear loadout?",
    "Afraid that raiding might require actual human interaction?",
    "Busy writing unit tests for your combat rotation?",
    "Worried that your mechanical keyboard might be too loud for voice chat?",
    "Too occupied trying to automate your raiding responsibilities?",
    "Afraid that the raid doesn't use your favorite JavaScript framework?",
    "Busy trying to explain why the raid needs blockchain technology?",
    "Worried that your stack overflow reputation might drop if you're away too long?",
    "Too occupied trying to turn the raid into a machine learning problem?",
    "Afraid that your git commit history might show you actually played the game?",
    "Busy trying to convince the guild that RAID is an acronym for 'Redundant Array of Independent Developers'?",

    # Lumberworkers
    "Too busy hugging trees to cut them down for raid?",
    "Afraid your flannel might clash with the raid tier set?",
    "Still trying to figure out how to use your axe on virtual trees?",
    "Busy growing your majestic lumberjack beard?",
    "Worried that raiding doesn't involve enough plaid?",
    "Too occupied singing to blue oxen to join the raid?",
    "Afraid that your calluses might give you an unfair advantage in clicking?",
    "Busy trying to craft a raid strategy using only wood?",
    "Worried that your Paul Bunyan cosplay might be too much for the raid?",
    "Too occupied trying to find the aggro radius of a tree?",
    "Afraid that your chainsaw might drown out the raid leader's calls?",
    "Busy trying to convince the guild to switch to an all-wooden gear set?",
    "Worried that your superior log-rolling skills won't translate to raiding?",
    "Too occupied trying to find the respawn timer on felled trees?",
    "Afraid that raiding might not count towards your daily cordage quota?",
    "Busy trying to apply real-world deforestation techniques to the game?",
    "Worried that your 'timber!' call might give away the group's position?",
    "Too occupied writing poetry about the romantic life of a lumberjack?",
    "Afraid that your natural musk might attract unwanted mobs during stealth sections?",
    "Busy trying to find a virtual forest dense enough to satisfy your tree-felling urges?",

    # People Still Stuck in College
    "Too busy changing your major for the 7th time to raid?",
    "Afraid raiding might interfere with your professional procrastination studies?",
    "Still trying to convince your raid leader that you need an extension on the boss fight?",
    "Busy trying to find a way to raid on the college's meal plan?",
    "Worried that raiding won't count towards your physical education credit?",
    "Too occupied writing a 20-page paper on the socioeconomic impacts of vendor trash?",
    "Afraid that your student loan debt might be bigger than the raid boss's health pool?",
    "Busy trying to turn your raid experience into a dissertation topic?",
    "Worried that your raid attendance might drop below your GPA?",
    "Too occupied trying to find the cheapest textbook version of 'Raiding 101'?",
    "Afraid that your parents might find out you're majoring in Azerothian Studies?",
    "Busy trying to convince your professor that raiding is a valid form of group project?",
    "Worried that you might have to pull an all-nighter for both studying and raiding?",
    "Too occupied trying to find a way to raid during your lecture?",
    "Afraid that your raid reflexes might be dulled by all that exam cramming?",
    "Busy trying to calculate how many ramen packets you can buy with raid gold?",
    "Worried that your student ID might not be valid for guild membership?",
    "Too occupied trying to find a work-study position as a virtual blacksmith?",
    "Afraid that your 'college experience' might not be complete without failing a raid?",
    "Busy trying to convince the financial aid office that epic mounts are educational expenses?",
        # Peruvian-themed
        "Too busy perfecting your ceviche recipe to join the raid?",
        "Afraid the raid might interfere with your daily llama-walking routine?",
        "Still trying to figure out how to use Inca-style stone fitting on the guild hall?",
        "Busy arguing that Machu Picchu would make a better raid location?",
        "Worried that your ping from the top of the Andes might be too high?",
        "Too occupied trying to trade raid loot for some quality alpaca wool?",
        "Afraid that your Nazca Lines map-reading skills won't help in the dungeon?",
        "Busy trying to convince the raid leader that pisco sour is the best pre-raid drink?",
        "Worried that your pan flute solo might attract more mobs?",
        "Too occupied trying to farm virtual potatoes at 4000 meters above sea level?",
        "Afraid that your chakana might clash with the guild tabard?",
        "Busy trying to tame a spectral guinea pig as your raiding pet?",
        "Worried that your Inca cola might spill on your keyboard during an intense fight?",
        "Too occupied building a chulpa to store your raid supplies?",
        "Afraid that your Quechua battle cries might confuse the raid group?",
        "Busy trying to replace all the raid buff food with cuy?",
        "Worried that your colorful Peruvian outfit might give away your position to the boss?",
        "Too occupied trying to weave a new raid cloak on your backstrap loom?",
        "Afraid that your constant craving for anticuchos might distract you from raid mechanics?",
        "Busy trying to convince the guild that Paddington Bear should be the new raid mascot?",
        "Too busy cultivating your neckbeard to raid?",
        "Still trying to pry your fingers off the keyboard after that 72-hour gaming marathon?",
        "Afraid the raid might interfere with your strict Mountain Dew IV drip schedule?",
        "Too occupied building your throne of empty energy drink cans?",
        "Worried raiding might dislodge the perfect imprint your body has made in your gaming chair?",
        "Busy writing a strongly worded forum post about how the game was better 10 years ago?",
        "Afraid of missing a single notification from your waifu mobile game?",
        "Too engrossed in your 'gamer girl bathwater' collection to raid?",
        "Worried that raiding might ruin your perfect farmer's tan from your monitor?",
        "Too busy min-maxing your character's appearance for the thousandth time?",
        "Afraid of missing a single frame of your favorite streamer's 24/7 broadcast?",
        "Too occupied reorganizing your anime figurine collection?",
        "Worried that raiding might disturb the delicate ecosystem growing in your unwashed gaming headset?",
        "Busy practicing your 'gamer rage' for your nonexistent Twitch audience?",
        "Afraid that leaving your room might cause you to spontaneously combust from sunlight exposure?",
        "Too engrossed in your heated gaming moment to join the raid?",
        "Worried that your RGB setup might malfunction if you're away for too long?",
        "Busy writing a 50-page guide on how to optimize inventory management?",
        "Afraid that your reflexes might've atrophied from only playing idle clicker games?",
        "Too occupied polishing your prized collection of limited edition Gamer Fuel cans?",
        "Worried that your muscle memory for the Konami code might fade if you raid?",
        "Busy trying to reach 'Prestige Level: Couch Potato'?",
        "Afraid that your fingers might cramp if you do anything other than spam 'pog' in Twitch chat?",
        "Too occupied maintaining your world record speedrun of 'longest time without showering'?",
        "Worried that raiding might interfere with your strict schedule of rage-quitting every other hour?",
        "Busy trying to mod Skyrim until it becomes sentient?",
        "Afraid that joining the raid might cause your WPM in typing games to drop below 200?",
        "Too occupied trying to figure out how to make your virtual waifu real?",
        "Worried that raiding might cause you to miss a new cosmetic item in the cash shop?",
        "Busy trying to achieve a perfect 0% body fat to 100% body Mountain Dew ratio?",
        "Afraid that leaving your gamer den might cause your collection of empty pizza boxes to collapse?",
        "Too occupied writing a doctoral thesis on the sociopolitical implications of teabagging?",
        "Worried that raiding might disturb your carefully cultivated gamer musk?",
        "Busy trying to break the world record for most Doritos consumed in one sitting?",
        "Afraid that joining the raid might cause you to miss a crucial 'git gud' moment?",
        "Too occupied trying to etch your gamertag into your skin using only energy drink condensation?",
        "Worried that raiding might interfere with your strict regimen of complaining about game balance?",
        "Busy trying to achieve symbiosis with your gaming chair?",
        "Afraid that your fingers might forget the intricate dance of APM if you take a break to raid?",
        "Too occupied trying to create the world's largest mountain of discarded instant ramen packets?",
        "Worried that raiding might cause your carefully maintained carpal tunnel to heal slightly?",
        "Busy trying to set a new record for longest continuous time spent in a loading screen?",
        "Afraid that joining the raid might cause you to miss a crucial mouse pad cleaning session?",
        "Too occupied trying to achieve the perfect 'gamer lean' for maximum performance?",
        "Worried that raiding might disturb the perfect layer of chip dust on your keyboard?",
        "Busy trying to decode the ancient gamer glyphs of 'Up Up Down Down Left Right Left Right B A'?",
        "Afraid that your eyeballs might detach if you look away from the screen for too long?",
        "Too occupied trying to become one with the lag?",
        "Worried that raiding might cause your vitamin D deficiency to improve slightly?",
        "Busy trying to achieve the perfect balance of caffeine and salt intake for maximum gaming performance?",
        "Afraid that joining the raid might cause you to miss a crucial comments section argument?",
        "Too occupied trying to farm that 0.0001% drop rate item?",
        "Worried that raiding might interfere with your strict schedule of blaming your team for every loss?",
        "Busy trying to unlock the secret 'touching grass' achievement?",
        "Afraid that your gaming socks might disintegrate if exposed to fresh air?",
        "Too occupied trying to build a real-life save point in case of gamer emergencies?",
        "Worried that raiding might cause your precision-tuned gamer gut to lose its perfect form?",
        "Busy trying to achieve a new high score in 'number of days without human contact'?",
        "Afraid that joining the raid might cause your eyes to remember how to blink?",
        "Too occupied trying to mine bitcoin with your gaming rig to afford more loot boxes?",
        "Worried that raiding might disturb the perfect ecosystem of your gamer gunk collection?",
        "Busy trying to master the art of gaming by osmosis by sleeping on your keyboard?",
        "Afraid that your fingers might forget their home row if you use them for anything but WASD?",
        "Too occupied trying to achieve the perfect ratio of game time to complaint time on forums?",
        "Worried that raiding might cause your carefully maintained repetitive strain injury to heal?",
        "Busy trying to unlock the mythical 'Day Mode' on your monitor?",
        "Afraid that joining the raid might cause you to miss a crucial energy drink restocking opportunity?",
        "Too occupied trying to achieve a symbiotic relationship with your gaming hardware?",
        "Worried that raiding might interfere with your strict schedule of yelling at kids in voice chat?",
        "Busy trying to break the world record for most consecutive hours spent in character creation?",
        "Afraid that your meticulously curated gamer calluses might soften if you take a break?",
        "Too occupied trying to reach the mythical 'Inbox Zero' in your game notification center?",
        "Worried that raiding might cause your perfectly optimized microtransaction strategy to falter?",
        "Busy trying to achieve the perfect blend of outrage and addiction that keeps you logging in daily?",
        "Afraid that joining the raid might cause you to miss a crucial moment in your favorite gacha game?",
        "Too occupied trying to master the art of gaming through interpretive dance?",
        "Worried that raiding might disturb the delicate balance of your hot pocket to body mass ratio?",
        "Busy trying to unlock the secret ending where you finally go outside?",
        "Afraid that your carefully maintained gamer slouch might improve if you sit up for a raid?",
        "Too occupied trying to achieve a perfect score in 'Procrastination Simulator 2024'?",
        "Worried that raiding might cause your meticulously crafted excuses for losing to become less believable?",
        "Busy trying to reach max level in 'Tutorial Skipping'?",
        "Afraid that joining the raid might cause your carefully curated list of games you'll 'play someday' to shrink?",
        "Too occupied trying to master the art of being carried through content while AFK?",
        "Worried that raiding might interfere with your groundbreaking research into 'gamer finger evolution'?",
        "Busy trying to achieve the world record for most consecutive jumps in an RPG town?",
        "Afraid that your perfectly timed gaming snack intervals might be disrupted by raiding?",
        "Too occupied trying to reach the skill cap in 'Shower Dodging'?",
        "Worried that raiding might cause your eyes to remember colors other than the glow of your LED setup?",
        "Busy trying to master the art of playing five mobile games simultaneously?",
        "Afraid that joining the raid might cause your carefully maintained gaming-induced insomnia to improve?",
        "Too occupied trying to achieve a world record speedrun in 'Uninstall and Reinstall'?",
        "Worried that raiding might disturb your precise calculations of pixels-per-second mouse movement?",
        "Busy evolving beyond the need for human interaction through pure gaming osmosis?",
        "Afraid that your hard-earned loot box opening calluses might soften if you raid instead?",
        "Too occupied trying to reach max level in every game on your 1000+ game backlog simultaneously?",
        "Worried that raiding might cause your meticulously maintained salt levels to drop below 'Dead Sea'?",
        "Busy trying to unlock the secret achievement 'Touch Grass' without actually going outside?"
    ]
    return random.choice(insults)